#ifndef _DATADOUBLE_IDL_
#define _DATADOUBLE_IDL_

#include "ossie/BULKIO/bio_runtimeStats.idl"
#include "ossie/BULKIO/bio_updateSRI.idl"

module BULKIO {

    interface dataDouble : ProvidesPortStatisticsProvider, updateSRI {
        void pushPacket(in PortTypes::DoubleSequence data, in PrecisionUTCTime T, in boolean EOS, in string streamID);
    };
};

#endif
