<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file is protected by Copyright.
    Please refer to the COPYRIGHT file distributed with this source distribution.

    This file is part of REDHAWK IDE.

    All rights reserved.  This program and the accompanying materials are made available under
    the terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html.
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extended" nsURI="http:///mil/jpeojtrs/sca/cf/extended.ecore"
    nsPrefix="ExtendedCF">
  <eClassifiers xsi:type="ecore:EClass" name="QueryablePort" instanceClassName="ExtendedCF.QueryablePort"
      abstract="true" interface="true" eSuperTypes="#//QueryablePortOperations cf.ecore#//Port cf.ecore#//IDLEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueryablePortOperations" instanceClassName="ExtendedCF.QueryablePortOperations"
      abstract="true" interface="true" eSuperTypes="cf.ecore#//PortOperations">
    <eOperations name="connections" eType="#//UsesConnectionArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UsesConnection" instanceClassName="ExtendedCF.UsesConnection"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UsesConnectionArray" instanceClassName="ExtendedCF.UsesConnection[]"
      serializable="false"/>
</ecore:EPackage>
