/* Generated By:JavaCC: Do not edit this line. ComplexParserCCConstants.java */
package mil.jpeojtrs.sca.util.math.parser.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface ComplexParserCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPLEX_MARKER = 7;
  /** RegularExpression Id. */
  int OCTALINT = 8;
  /** RegularExpression Id. */
  int DECIMALINT = 9;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 10;
  /** RegularExpression Id. */
  int FLOATONE = 11;
  /** RegularExpression Id. */
  int FLOATTWO = 12;
  /** RegularExpression Id. */
  int CHARACTER = 13;
  /** RegularExpression Id. */
  int STRING = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"-\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"+\"",
    "<COMPLEX_MARKER>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
  };

}
