/* Generated By:JavaCC: Do not edit this line. ComplexParserCCConstants.java */
/**
 * This file is protected by Copyright.
 * Please refer to the COPYRIGHT file distributed with this source distribution.
 *
 * This file is part of REDHAWK IDE.
 *
 * All rights reserved.  This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html.
 *
 */
package mil.jpeojtrs.sca.util.math.parser.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComplexParserCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPLEX_MARKER = 7;
  /** RegularExpression Id. */
  int OCTALINT = 8;
  /** RegularExpression Id. */
  int DECIMALINT = 9;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 10;
  /** RegularExpression Id. */
  int FLOATONE = 11;
  /** RegularExpression Id. */
  int FLOATTWO = 12;
  /** RegularExpression Id. */
  int CHARACTER = 13;
  /** RegularExpression Id. */
  int STRING = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"-\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"+\"",
    "<COMPLEX_MARKER>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
  };

}
