package FRONTEND;


/**
* FRONTEND/_GPSStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public class _GPSStub extends org.omg.CORBA.portable.ObjectImpl implements FRONTEND.GPS
{


  /** Updates as necessary */
  public FRONTEND.GPSInfo gps_info ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_gps_info", true);
                $in = _invoke ($out);
                FRONTEND.GPSInfo $result = FRONTEND.GPSInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return gps_info (        );
            } finally {
                _releaseReply ($in);
            }
  } // gps_info


  /** Updates as necessary */
  public void gps_info (FRONTEND.GPSInfo newGps_info)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_gps_info", true);
                FRONTEND.GPSInfoHelper.write ($out, newGps_info);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                gps_info (newGps_info        );
            } finally {
                _releaseReply ($in);
            }
  } // gps_info


  /** Main timing structure. If pososition is not known, set position valid to false */
  public FRONTEND.GpsTimePos gps_time_pos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_gps_time_pos", true);
                $in = _invoke ($out);
                FRONTEND.GpsTimePos $result = FRONTEND.GpsTimePosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return gps_time_pos (        );
            } finally {
                _releaseReply ($in);
            }
  } // gps_time_pos


  /** Main timing structure. If pososition is not known, set position valid to false */
  public void gps_time_pos (FRONTEND.GpsTimePos newGps_time_pos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_gps_time_pos", true);
                FRONTEND.GpsTimePosHelper.write ($out, newGps_time_pos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                gps_time_pos (newGps_time_pos        );
            } finally {
                _releaseReply ($in);
            }
  } // gps_time_pos

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FRONTEND/GPS:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GPSStub
