package FRONTEND;


/**
* FRONTEND/AnalogTunerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/TunerControl.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface AnalogTunerOperations  extends FRONTEND.FrontendTunerOperations
{

  /** Set/Get tuner center frequency */
  void setTunerCenterFrequency (String id, double freq) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  double getTunerCenterFrequency (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /**  Set/Get tuner bandwidth */
  void setTunerBandwidth (String id, double bw) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  double getTunerBandwidth (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /**  MGC/AGC  */
  void setTunerAgcEnable (String id, boolean enable) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  boolean getTunerAgcEnable (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /**  MGC Gain (where negative gain is attentuation)*/
  void setTunerGain (String id, float gain) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  float getTunerGain (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /**  Tuner Reference Source: 0 = internal,  1 = external*/
  void setTunerReferenceSource (String id, int source) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  int getTunerReferenceSource (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /**  Enable/Disable Tuner - Expected to keep current tuner settings on a disable and an EOS to be sent */
  void setTunerEnable (String id, boolean enable) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  boolean getTunerEnable (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
} // interface AnalogTunerOperations
