package FRONTEND;

/**
* FRONTEND/AntennaInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class AntennaInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.AntennaInfo value = null;

  public AntennaInfoHolder ()
  {
  }

  public AntennaInfoHolder (FRONTEND.AntennaInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.AntennaInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.AntennaInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.AntennaInfoHelper.type ();
  }

}
