package FRONTEND;


/**
* FRONTEND/AntennaInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class AntennaInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String type = null;
  public String size = null;
  public String description = null;

  public AntennaInfo ()
  {
  } // ctor

  public AntennaInfo (String _name, String _type, String _size, String _description)
  {
    name = _name;
    type = _type;
    size = _size;
    description = _description;
  } // ctor

} // class AntennaInfo
