package FRONTEND;


/**
* FRONTEND/AttitudeInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class AttitudeInfo implements org.omg.CORBA.portable.IDLEntity
{
  public boolean valid = false;
  public double pitch = (double)0;

  /** Default Unit: Degrees */
  public double yaw = (double)0;

  /** Default Unit: Degrees */
  public double roll = (double)0;

  public AttitudeInfo ()
  {
  } // ctor

  public AttitudeInfo (boolean _valid, double _pitch, double _yaw, double _roll)
  {
    valid = _valid;
    pitch = _pitch;
    yaw = _yaw;
    roll = _roll;
  } // ctor

} // class AttitudeInfo
