package FRONTEND;


/**
* FRONTEND/BadParameterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class BadParameterException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public BadParameterException ()
  {
    super(BadParameterExceptionHelper.id());
  } // ctor

  public BadParameterException (String _msg)
  {
    super(BadParameterExceptionHelper.id());
    msg = _msg;
  } // ctor


  public BadParameterException (String $reason, String _msg)
  {
    super(BadParameterExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class BadParameterException
