package FRONTEND;


/**
* FRONTEND/DigitalTunerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/TunerControl.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface DigitalTunerOperations  extends FRONTEND.AnalogTunerOperations
{

  /**  Set output sample rate  */
  void setTunerOutputSampleRate (String id, double sr) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
  double getTunerOutputSampleRate (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
} // interface DigitalTunerOperations
