package FRONTEND;


/**
* FRONTEND/FE_RFINFO_DEVICE_KIND.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface FE_RFINFO_DEVICE_KIND
{

  /** Device Kind */
  public static final String value = "FRONTEND::RFINFO";
}
