package FRONTEND;


/**
* FRONTEND/FeedInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class FeedInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String polarization = null;
  public FRONTEND.FreqRange freq_range = null;

  public FeedInfo ()
  {
  } // ctor

  public FeedInfo (String _name, String _polarization, FRONTEND.FreqRange _freq_range)
  {
    name = _name;
    polarization = _polarization;
    freq_range = _freq_range;
  } // ctor

} // class FeedInfo
