package FRONTEND;

/**
* FRONTEND/FeedInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class FeedInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.FeedInfo value = null;

  public FeedInfoHolder ()
  {
  }

  public FeedInfoHolder (FRONTEND.FeedInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.FeedInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.FeedInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.FeedInfoHelper.type ();
  }

}
