package FRONTEND;


/**
* FRONTEND/FreqRange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class FreqRange implements org.omg.CORBA.portable.IDLEntity
{
  public double min_val = (double)0;
  public double max_val = (double)0;
  public double values[] = null;

  public FreqRange ()
  {
  } // ctor

  public FreqRange (double _min_val, double _max_val, double[] _values)
  {
    min_val = _min_val;
    max_val = _max_val;
    values = _values;
  } // ctor

} // class FreqRange
