package FRONTEND;


/**
* FRONTEND/FrontendTunerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/TunerControl.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*************************/
public interface FrontendTunerOperations 
{

  /** Get the type of tuner (ie- RX or DDC) associated with this allocation id*/
  String getTunerType (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /** Returns whether this allocation id has control (modification privledges) over the tuner*/
  boolean getTunerDeviceControl (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /** Retrieves the group id (may be empty) for this allocation id */
  String getTunerGroupId (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /** Retrieves the rf flow id (may be empty) for this allocation id */
  String getTunerRfFlowId (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;

  /** Key/Value pair of entire tuner status structure */
  CF.DataType[] getTunerStatus (String id) throws FRONTEND.FrontendException, FRONTEND.BadParameterException, FRONTEND.NotSupportedException;
} // interface FrontendTunerOperations
