package FRONTEND;


/**
* FRONTEND/FrontendException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public final class FrontendException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public FrontendException ()
  {
    super(FrontendExceptionHelper.id());
  } // ctor

  public FrontendException (String _msg)
  {
    super(FrontendExceptionHelper.id());
    msg = _msg;
  } // ctor


  public FrontendException (String $reason, String _msg)
  {
    super(FrontendExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class FrontendException
