package FRONTEND;

/**
* FRONTEND/GPSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public final class GPSHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.GPS value = null;

  public GPSHolder ()
  {
  }

  public GPSHolder (FRONTEND.GPS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.GPSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.GPSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.GPSHelper.type ();
  }

}
