package FRONTEND;

/**
* FRONTEND/GPSInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class GPSInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.GPSInfo value = null;

  public GPSInfoHolder ()
  {
  }

  public GPSInfoHolder (FRONTEND.GPSInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.GPSInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.GPSInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.GPSInfoHelper.type ();
  }

}
