package FRONTEND;


/**
* FRONTEND/GPSInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class GPSInfoHelper
{
  private static String  _id = "IDL:FRONTEND/GPSInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.GPSInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.GPSInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [15];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "source_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rf_flow_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "mode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "fom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "tfom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "datumID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[6] = new org.omg.CORBA.StructMember (
            "time_offset",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[7] = new org.omg.CORBA.StructMember (
            "freq_offset",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[8] = new org.omg.CORBA.StructMember (
            "time_variance",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[9] = new org.omg.CORBA.StructMember (
            "freq_variance",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[10] = new org.omg.CORBA.StructMember (
            "satellite_count",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[11] = new org.omg.CORBA.StructMember (
            "snr",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[12] = new org.omg.CORBA.StructMember (
            "status_message",
            _tcOf_members0,
            null);
          _tcOf_members0 = BULKIO.PrecisionUTCTimeHelper.type ();
          _members0[13] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = CF.DataTypeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CF.PropertiesHelper.id (), "Properties", _tcOf_members0);
          _members0[14] = new org.omg.CORBA.StructMember (
            "additional_info",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FRONTEND.GPSInfoHelper.id (), "GPSInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.GPSInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.GPSInfo value = new FRONTEND.GPSInfo ();
    value.source_id = istream.read_string ();
    value.rf_flow_id = istream.read_string ();
    value.mode = istream.read_string ();
    value.fom = istream.read_long ();
    value.tfom = istream.read_long ();
    value.datumID = istream.read_long ();
    value.time_offset = istream.read_double ();
    value.freq_offset = istream.read_double ();
    value.time_variance = istream.read_double ();
    value.freq_variance = istream.read_double ();
    value.satellite_count = istream.read_short ();
    value.snr = istream.read_float ();
    value.status_message = istream.read_string ();
    value.timestamp = BULKIO.PrecisionUTCTimeHelper.read (istream);
    value.additional_info = CF.PropertiesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.GPSInfo value)
  {
    ostream.write_string (value.source_id);
    ostream.write_string (value.rf_flow_id);
    ostream.write_string (value.mode);
    ostream.write_long (value.fom);
    ostream.write_long (value.tfom);
    ostream.write_long (value.datumID);
    ostream.write_double (value.time_offset);
    ostream.write_double (value.freq_offset);
    ostream.write_double (value.time_variance);
    ostream.write_double (value.freq_variance);
    ostream.write_short (value.satellite_count);
    ostream.write_float (value.snr);
    ostream.write_string (value.status_message);
    BULKIO.PrecisionUTCTimeHelper.write (ostream, value.timestamp);
    CF.PropertiesHelper.write (ostream, value.additional_info);
  }

}
