package FRONTEND;


/**
* FRONTEND/GPSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public abstract class GPSPOA extends org.omg.PortableServer.Servant
 implements FRONTEND.GPSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_gps_info", new java.lang.Integer (0));
    _methods.put ("_set_gps_info", new java.lang.Integer (1));
    _methods.put ("_get_gps_time_pos", new java.lang.Integer (2));
    _methods.put ("_set_gps_time_pos", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /** Updates as necessary */
       case 0:  // FRONTEND/GPS/_get_gps_info
       {
         FRONTEND.GPSInfo $result = null;
         $result = this.gps_info ();
         out = $rh.createReply();
         FRONTEND.GPSInfoHelper.write (out, $result);
         break;
       }


  /** Updates as necessary */
       case 1:  // FRONTEND/GPS/_set_gps_info
       {
         FRONTEND.GPSInfo newGps_info = FRONTEND.GPSInfoHelper.read (in);
         this.gps_info (newGps_info);
         out = $rh.createReply();
         break;
       }


  /** Main timing structure. If pososition is not known, set position valid to false */
       case 2:  // FRONTEND/GPS/_get_gps_time_pos
       {
         FRONTEND.GpsTimePos $result = null;
         $result = this.gps_time_pos ();
         out = $rh.createReply();
         FRONTEND.GpsTimePosHelper.write (out, $result);
         break;
       }


  /** Main timing structure. If pososition is not known, set position valid to false */
       case 3:  // FRONTEND/GPS/_set_gps_time_pos
       {
         FRONTEND.GpsTimePos newGps_time_pos = FRONTEND.GpsTimePosHelper.read (in);
         this.gps_time_pos (newGps_time_pos);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FRONTEND/GPS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GPS _this() 
  {
    return GPSHelper.narrow(
    super._this_object());
  }

  public GPS _this(org.omg.CORBA.ORB orb) 
  {
    return GPSHelper.narrow(
    super._this_object(orb));
  }


} // class GPSPOA
