package FRONTEND;


/**
* FRONTEND/GpsTimePosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class GpsTimePosHelper
{
  private static String  _id = "IDL:FRONTEND/GpsTimePos:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.GpsTimePos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.GpsTimePos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = FRONTEND.PositionInfoHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "position",
            _tcOf_members0,
            null);
          _tcOf_members0 = BULKIO.PrecisionUTCTimeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FRONTEND.GpsTimePosHelper.id (), "GpsTimePos", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.GpsTimePos read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.GpsTimePos value = new FRONTEND.GpsTimePos ();
    value.position = FRONTEND.PositionInfoHelper.read (istream);
    value.timestamp = BULKIO.PrecisionUTCTimeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.GpsTimePos value)
  {
    FRONTEND.PositionInfoHelper.write (ostream, value.position);
    BULKIO.PrecisionUTCTimeHelper.write (ostream, value.timestamp);
  }

}
