package FRONTEND;


/**
* FRONTEND/GpsTimePos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/GPS.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class GpsTimePos implements org.omg.CORBA.portable.IDLEntity
{
  public FRONTEND.PositionInfo position = null;
  public BULKIO.PrecisionUTCTime timestamp = null;

  public GpsTimePos ()
  {
  } // ctor

  public GpsTimePos (FRONTEND.PositionInfo _position, BULKIO.PrecisionUTCTime _timestamp)
  {
    position = _position;
    timestamp = _timestamp;
  } // ctor

} // class GpsTimePos
