package FRONTEND;


/**
* FRONTEND/NavDataPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/NavigationData.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public class NavDataPOATie extends NavDataPOA
{

  // Constructors

  public NavDataPOATie ( FRONTEND.NavDataOperations delegate ) {
      this._impl = delegate;
  }
  public NavDataPOATie ( FRONTEND.NavDataOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public FRONTEND.NavDataOperations _delegate() {
      return this._impl;
  }
  public void _delegate (FRONTEND.NavDataOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public FRONTEND.NavigationPacket nav_packet ()
  {
    return _impl.nav_packet();
  } // nav_packet
  public void nav_packet (FRONTEND.NavigationPacket newNav_packet)
  {
    _impl.nav_packet(newNav_packet);
  } // nav_packet

  private FRONTEND.NavDataOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class NavDataPOATie
