package FRONTEND;


/**
* FRONTEND/NavDataOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/NavigationData.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public interface NavDataOperations 
{
  FRONTEND.NavigationPacket nav_packet ();
  void nav_packet (FRONTEND.NavigationPacket newNav_packet);
} // interface NavDataOperations
