package FRONTEND;


/**
* FRONTEND/NavDataPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/NavigationData.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/************************/
public abstract class NavDataPOA extends org.omg.PortableServer.Servant
 implements FRONTEND.NavDataOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_nav_packet", new java.lang.Integer (0));
    _methods.put ("_set_nav_packet", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FRONTEND/NavData/_get_nav_packet
       {
         FRONTEND.NavigationPacket $result = null;
         $result = this.nav_packet ();
         out = $rh.createReply();
         FRONTEND.NavigationPacketHelper.write (out, $result);
         break;
       }

       case 1:  // FRONTEND/NavData/_set_nav_packet
       {
         FRONTEND.NavigationPacket newNav_packet = FRONTEND.NavigationPacketHelper.read (in);
         this.nav_packet (newNav_packet);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FRONTEND/NavData:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NavData _this() 
  {
    return NavDataHelper.narrow(
    super._this_object());
  }

  public NavData _this(org.omg.CORBA.ORB orb) 
  {
    return NavDataHelper.narrow(
    super._this_object(orb));
  }


} // class NavDataPOA
