package FRONTEND;


/**
* FRONTEND/NavigationPacketHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/NavigationData.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class NavigationPacketHelper
{
  private static String  _id = "IDL:FRONTEND/NavigationPacket:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.NavigationPacket that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.NavigationPacket extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "source_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rf_flow_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.PositionInfoHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "position",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.CartesianPositionInfoHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "cposition",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.VelocityInfoHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "velocity",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.AccelerationInfoHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "acceleration",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.AttitudeInfoHelper.type ();
          _members0[6] = new org.omg.CORBA.StructMember (
            "attitude",
            _tcOf_members0,
            null);
          _tcOf_members0 = BULKIO.PrecisionUTCTimeHelper.type ();
          _members0[7] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = CF.DataTypeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CF.PropertiesHelper.id (), "Properties", _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "additional_info",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FRONTEND.NavigationPacketHelper.id (), "NavigationPacket", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.NavigationPacket read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.NavigationPacket value = new FRONTEND.NavigationPacket ();
    value.source_id = istream.read_string ();
    value.rf_flow_id = istream.read_string ();
    value.position = FRONTEND.PositionInfoHelper.read (istream);
    value.cposition = FRONTEND.CartesianPositionInfoHelper.read (istream);
    value.velocity = FRONTEND.VelocityInfoHelper.read (istream);
    value.acceleration = FRONTEND.AccelerationInfoHelper.read (istream);
    value.attitude = FRONTEND.AttitudeInfoHelper.read (istream);
    value.timestamp = BULKIO.PrecisionUTCTimeHelper.read (istream);
    value.additional_info = CF.PropertiesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.NavigationPacket value)
  {
    ostream.write_string (value.source_id);
    ostream.write_string (value.rf_flow_id);
    FRONTEND.PositionInfoHelper.write (ostream, value.position);
    FRONTEND.CartesianPositionInfoHelper.write (ostream, value.cposition);
    FRONTEND.VelocityInfoHelper.write (ostream, value.velocity);
    FRONTEND.AccelerationInfoHelper.write (ostream, value.acceleration);
    FRONTEND.AttitudeInfoHelper.write (ostream, value.attitude);
    BULKIO.PrecisionUTCTimeHelper.write (ostream, value.timestamp);
    CF.PropertiesHelper.write (ostream, value.additional_info);
  }

}
