package FRONTEND;


/**
* FRONTEND/NavigationPacket.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/NavigationData.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class NavigationPacket implements org.omg.CORBA.portable.IDLEntity
{
  public String source_id = null;

  /** NAV source identifier */
  public String rf_flow_id = null;

  /** positional data */
  public FRONTEND.PositionInfo position = null;
  public FRONTEND.CartesianPositionInfo cposition = null;
  public FRONTEND.VelocityInfo velocity = null;
  public FRONTEND.AccelerationInfo acceleration = null;
  public FRONTEND.AttitudeInfo attitude = null;

  /** timestamp */
  public BULKIO.PrecisionUTCTime timestamp = null;

  /** Allows for keyword expansion*/
  public CF.DataType additional_info[] = null;

  public NavigationPacket ()
  {
  } // ctor

  public NavigationPacket (String _source_id, String _rf_flow_id, FRONTEND.PositionInfo _position, FRONTEND.CartesianPositionInfo _cposition, FRONTEND.VelocityInfo _velocity, FRONTEND.AccelerationInfo _acceleration, FRONTEND.AttitudeInfo _attitude, BULKIO.PrecisionUTCTime _timestamp, CF.DataType[] _additional_info)
  {
    source_id = _source_id;
    rf_flow_id = _rf_flow_id;
    position = _position;
    cposition = _cposition;
    velocity = _velocity;
    acceleration = _acceleration;
    attitude = _attitude;
    timestamp = _timestamp;
    additional_info = _additional_info;
  } // ctor

} // class NavigationPacket
