package FRONTEND;

/**
* FRONTEND/NotSupportedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class NotSupportedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.NotSupportedException value = null;

  public NotSupportedExceptionHolder ()
  {
  }

  public NotSupportedExceptionHolder (FRONTEND.NotSupportedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.NotSupportedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.NotSupportedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.NotSupportedExceptionHelper.type ();
  }

}
