package FRONTEND;


/**
* FRONTEND/NotSupportedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class NotSupportedException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public NotSupportedException ()
  {
    super(NotSupportedExceptionHelper.id());
  } // ctor

  public NotSupportedException (String _msg)
  {
    super(NotSupportedExceptionHelper.id());
    msg = _msg;
  } // ctor


  public NotSupportedException (String $reason, String _msg)
  {
    super(NotSupportedExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class NotSupportedException
