package FRONTEND;


/**
* FRONTEND/PathDelay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class PathDelay implements org.omg.CORBA.portable.IDLEntity
{
  public double freq = (double)0;
  public double delay_ns = (double)0;

  public PathDelay ()
  {
  } // ctor

  public PathDelay (double _freq, double _delay_ns)
  {
    freq = _freq;
    delay_ns = _delay_ns;
  } // ctor

} // class PathDelay
