package FRONTEND;

/**
* FRONTEND/PathDelayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class PathDelayHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.PathDelay value = null;

  public PathDelayHolder ()
  {
  }

  public PathDelayHolder (FRONTEND.PathDelay initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.PathDelayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.PathDelayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.PathDelayHelper.type ();
  }

}
