package FRONTEND;


/**
* FRONTEND/PathDelaysHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class PathDelaysHelper
{
  private static String  _id = "IDL:FRONTEND/PathDelays:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.PathDelay[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.PathDelay[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = FRONTEND.PathDelayHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (FRONTEND.PathDelaysHelper.id (), "PathDelays", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.PathDelay[] read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.PathDelay value[] = null;
    int _len0 = istream.read_long ();
    value = new FRONTEND.PathDelay[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = FRONTEND.PathDelayHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.PathDelay[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      FRONTEND.PathDelayHelper.write (ostream, value[_i0]);
  }

}
