package FRONTEND;


/**
* FRONTEND/PAYLOAD_PCAP.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface PAYLOAD_PCAP
{
  public static final String value = "PCAP";
}
