package FRONTEND;


/**
* FRONTEND/PositionInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class PositionInfo implements org.omg.CORBA.portable.IDLEntity
{
  public boolean valid = false;
  public String datum = null;

  /** Default: DATUM_WGS84 */
  public double lat = (double)0;

  /** Default Unit: Degrees */
  public double lon = (double)0;

  /** Default Unit: Degrees */
  public double alt = (double)0;

  public PositionInfo ()
  {
  } // ctor

  public PositionInfo (boolean _valid, String _datum, double _lat, double _lon, double _alt)
  {
    valid = _valid;
    datum = _datum;
    lat = _lat;
    lon = _lon;
    alt = _alt;
  } // ctor

} // class PositionInfo
