package FRONTEND;

/**
* FRONTEND/PositionInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class PositionInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.PositionInfo value = null;

  public PositionInfoHolder ()
  {
  }

  public PositionInfoHolder (FRONTEND.PositionInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.PositionInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.PositionInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.PositionInfoHelper.type ();
  }

}
