package FRONTEND;


/**
* FRONTEND/REFERNCE_SOURCE_INTERNAL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/TunerControl.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface REFERNCE_SOURCE_INTERNAL
{

  /** Output format for digital tuners */
  public static final int value = (int)(0);
}
