package FRONTEND;

/**
* FRONTEND/RFInfoPktHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class RFInfoPktHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.RFInfoPkt value = null;

  public RFInfoPktHolder ()
  {
  }

  public RFInfoPktHolder (FRONTEND.RFInfoPkt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.RFInfoPktHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.RFInfoPktHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.RFInfoPktHelper.type ();
  }

}
