package FRONTEND;


/**
* FRONTEND/RFInfoPktSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class RFInfoPktSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.RFInfoPkt value[] = null;

  public RFInfoPktSequenceHolder ()
  {
  }

  public RFInfoPktSequenceHolder (FRONTEND.RFInfoPkt[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.RFInfoPktSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.RFInfoPktSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.RFInfoPktSequenceHelper.type ();
  }

}
