package FRONTEND;


/**
* FRONTEND/RFInfoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*******************************/
public interface RFInfoOperations 
{

  /** unique string that flows with data to describe its RF source*/
  String rf_flow_id ();

  /** unique string that flows with data to describe its RF source*/
  void rf_flow_id (String newRf_flow_id);

  /** generic container to describe RF frontend */
  FRONTEND.RFInfoPkt rfinfo_pkt ();

  /** generic container to describe RF frontend */
  void rfinfo_pkt (FRONTEND.RFInfoPkt newRfinfo_pkt);
} // interface RFInfoOperations
