package FRONTEND;

/**
* FRONTEND/RFInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*******************************/
public final class RFInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.RFInfo value = null;

  public RFInfoHolder ()
  {
  }

  public RFInfoHolder (FRONTEND.RFInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.RFInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.RFInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.RFInfoHelper.type ();
  }

}
