package FRONTEND;


/**
* FRONTEND/RFInfoPktHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class RFInfoPktHelper
{
  private static String  _id = "IDL:FRONTEND/RFInfoPkt:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.RFInfoPkt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.RFInfoPkt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "rf_flow_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rf_center_freq",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "rf_bandwidth",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "if_center_freq",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "spectrum_inverted",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.SensorInfoHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "sensor",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.PathDelayHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (FRONTEND.PathDelaysHelper.id (), "PathDelays", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "ext_path_delays",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.RFCapabilitiesHelper.type ();
          _members0[7] = new org.omg.CORBA.StructMember (
            "capabilities",
            _tcOf_members0,
            null);
          _tcOf_members0 = CF.DataTypeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (CF.PropertiesHelper.id (), "Properties", _tcOf_members0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "additional_info",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FRONTEND.RFInfoPktHelper.id (), "RFInfoPkt", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.RFInfoPkt read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.RFInfoPkt value = new FRONTEND.RFInfoPkt ();
    value.rf_flow_id = istream.read_string ();
    value.rf_center_freq = istream.read_double ();
    value.rf_bandwidth = istream.read_double ();
    value.if_center_freq = istream.read_double ();
    value.spectrum_inverted = istream.read_boolean ();
    value.sensor = FRONTEND.SensorInfoHelper.read (istream);
    value.ext_path_delays = FRONTEND.PathDelaysHelper.read (istream);
    value.capabilities = FRONTEND.RFCapabilitiesHelper.read (istream);
    value.additional_info = CF.PropertiesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.RFInfoPkt value)
  {
    ostream.write_string (value.rf_flow_id);
    ostream.write_double (value.rf_center_freq);
    ostream.write_double (value.rf_bandwidth);
    ostream.write_double (value.if_center_freq);
    ostream.write_boolean (value.spectrum_inverted);
    FRONTEND.SensorInfoHelper.write (ostream, value.sensor);
    FRONTEND.PathDelaysHelper.write (ostream, value.ext_path_delays);
    FRONTEND.RFCapabilitiesHelper.write (ostream, value.capabilities);
    CF.PropertiesHelper.write (ostream, value.additional_info);
  }

}
