package FRONTEND;


/**
* FRONTEND/RFSourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*********************************/
public interface RFSourceOperations 
{

  /** A list of all possible rf inputs that this source could switch to **/
  FRONTEND.RFInfoPkt[] available_rf_inputs ();

  /** A list of all possible rf inputs that this source could switch to **/
  void available_rf_inputs (FRONTEND.RFInfoPkt[] newAvailable_rf_inputs);

  /** The current select source that is being output **/
  FRONTEND.RFInfoPkt current_rf_input ();

  /** The current select source that is being output **/
  void current_rf_input (FRONTEND.RFInfoPkt newCurrent_rf_input);
} // interface RFSourceOperations
