package FRONTEND;


/**
* FRONTEND/RFSourceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*********************************/
abstract public class RFSourceHelper
{
  private static String  _id = "IDL:FRONTEND/RFSource:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.RFSource that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.RFSource extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FRONTEND.RFSourceHelper.id (), "RFSource");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.RFSource read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RFSourceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.RFSource value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FRONTEND.RFSource narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FRONTEND.RFSource)
      return (FRONTEND.RFSource)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FRONTEND._RFSourceStub stub = new FRONTEND._RFSourceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FRONTEND.RFSource unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FRONTEND.RFSource)
      return (FRONTEND.RFSource)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FRONTEND._RFSourceStub stub = new FRONTEND._RFSourceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
