package FRONTEND;


/**
* FRONTEND/RFSourcePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/RFInfo.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/


/*********************************/
public class RFSourcePOATie extends RFSourcePOA
{

  // Constructors

  public RFSourcePOATie ( FRONTEND.RFSourceOperations delegate ) {
      this._impl = delegate;
  }
  public RFSourcePOATie ( FRONTEND.RFSourceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public FRONTEND.RFSourceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (FRONTEND.RFSourceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }

  /** A list of all possible rf inputs that this source could switch to **/
  public FRONTEND.RFInfoPkt[] available_rf_inputs ()
  {
    return _impl.available_rf_inputs();
  } // available_rf_inputs

  /** A list of all possible rf inputs that this source could switch to **/
  public void available_rf_inputs (FRONTEND.RFInfoPkt[] newAvailable_rf_inputs)
  {
    _impl.available_rf_inputs(newAvailable_rf_inputs);
  } // available_rf_inputs


  /** The current select source that is being output **/
  public FRONTEND.RFInfoPkt current_rf_input ()
  {
    return _impl.current_rf_input();
  } // current_rf_input

  /** The current select source that is being output **/
  public void current_rf_input (FRONTEND.RFInfoPkt newCurrent_rf_input)
  {
    _impl.current_rf_input(newCurrent_rf_input);
  } // current_rf_input

  private FRONTEND.RFSourceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RFSourcePOATie
