package FRONTEND;


/**
* FRONTEND/SensorInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

abstract public class SensorInfoHelper
{
  private static String  _id = "IDL:FRONTEND/SensorInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, FRONTEND.SensorInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FRONTEND.SensorInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "mission",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "collector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "rx",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.AntennaInfoHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "antenna",
            _tcOf_members0,
            null);
          _tcOf_members0 = FRONTEND.FeedInfoHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "feed",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FRONTEND.SensorInfoHelper.id (), "SensorInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FRONTEND.SensorInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    FRONTEND.SensorInfo value = new FRONTEND.SensorInfo ();
    value.mission = istream.read_string ();
    value.collector = istream.read_string ();
    value.rx = istream.read_string ();
    value.antenna = FRONTEND.AntennaInfoHelper.read (istream);
    value.feed = FRONTEND.FeedInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FRONTEND.SensorInfo value)
  {
    ostream.write_string (value.mission);
    ostream.write_string (value.collector);
    ostream.write_string (value.rx);
    FRONTEND.AntennaInfoHelper.write (ostream, value.antenna);
    FRONTEND.FeedInfoHelper.write (ostream, value.feed);
  }

}
