package FRONTEND;


/**
* FRONTEND/SensorInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class SensorInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String mission = null;
  public String collector = null;
  public String rx = null;
  public FRONTEND.AntennaInfo antenna = null;
  public FRONTEND.FeedInfo feed = null;

  public SensorInfo ()
  {
  } // ctor

  public SensorInfo (String _mission, String _collector, String _rx, FRONTEND.AntennaInfo _antenna, FRONTEND.FeedInfo _feed)
  {
    mission = _mission;
    collector = _collector;
    rx = _rx;
    antenna = _antenna;
    feed = _feed;
  } // ctor

} // class SensorInfo
