package FRONTEND;

/**
* FRONTEND/SensorInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class SensorInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONTEND.SensorInfo value = null;

  public SensorInfoHolder ()
  {
  }

  public SensorInfoHolder (FRONTEND.SensorInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONTEND.SensorInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONTEND.SensorInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONTEND.SensorInfoHelper.type ();
  }

}
