package FRONTEND;


/**
* FRONTEND/TUNER_TYPE_TX.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/TunerControl.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public interface TUNER_TYPE_TX
{

  /** --- Tuner Types - Expandable list of supported FE types --- */
  public static final String value = "TX";
}
