package FRONTEND;


/**
* FRONTEND/VelocityInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /data/Workspaces/dev_1-10_workspace/mil.jpeojtrs.sca/plugins/idl.frontend/idl/redhawk/FRONTEND/Frontend.idl
* Wednesday, December 18, 2013 5:32:24 PM EST
*/

public final class VelocityInfo implements org.omg.CORBA.portable.IDLEntity
{
  public boolean valid = false;
  public String datum = null;

  /** Default: DATUM_WGS84 */
  public String coordinate_system = null;

  /** Values: CS_ECF, CS_ENU, CS_NED **/
  public double x = (double)0;

  /** Default Unit: Meters/Second */
  public double y = (double)0;

  /** Default Unit: Meters/Second */
  public double z = (double)0;

  public VelocityInfo ()
  {
  } // ctor

  public VelocityInfo (boolean _valid, String _datum, String _coordinate_system, double _x, double _y, double _z)
  {
    valid = _valid;
    datum = _datum;
    coordinate_system = _coordinate_system;
    x = _x;
    y = _y;
    z = _z;
  } // ctor

} // class VelocityInfo
